### ISSUE TITLE
Wakelock issue

### ISSUE THREAD

**Issue by Jostian** [kdrag0n/velocity_dream#1] opened 2018-10-09 18:35 UTC
Seems abox wakelock is draining battery while phone is in sleep/standby on latest kernel version, just wanted to mention this

**Comment by kdrag0n** [comment] 2018-10-10 06:30
I can't reproduce this. What ROM? Have you been using speakers or the headphone jack? Which device model?

**Comment by Jostian** [comment] 2018-10-10 06:38
No speaker or headohone use, phone was idle (during night) S8+ SolDier ROM 10.2, tried with other kernel and abox wakelock disappears, then reinstalled your kernel and within 3 hours abox back at top of wakelock list, but have no idea what the issue could be. Thanks

**Comment by kdrag0n** [comment] 2018-10-10 06:44
Is battery life actually affected by this?

Please take a screenshot of the battery usage graph and apps in Settings.
It'd also be helpful if you could screenshot the by-app usage and kernel
wakelock list in GSam Battery Monitor.

**Comment by Jostian** [comment] 2018-10-10 06:46
I lost 14% during the night, where i normally lose about 3% so yes the is impact on battery, will see if i can get some screenshots for you over the next day or so, thanks

**Comment by kdrag0n** [comment] 2018-10-14 19:58
@Jostian any update?

**Comment by Jostian** [comment] 2018-10-14 20:02
Tried to install R9 but after installing it, everytime the screen goes off the phone reboots, so can't check the abox wakelock... So not sure what to do, thought I'd wait for R10 and then try again. J

**Comment by kdrag0n** [comment] 2018-10-15 06:29
Delete the hidden .velocity_settings file in /sdcard (internal storage). Then reflash the kernel and choose Permissive when asked. If that doesn't fix it it's probably the I/O scheduler switcher which has been removed and will not be present in r10.

**Comment by Jostian** [comment] 2018-10-15 07:33
Yip, someone on the forum suggested that and i deleted the settings file and selected permissive but the same thing happens, reboot on screen off.

**Comment by Jostian** [comment] 2018-10-16 17:26
Any idea when a revised version with the i/o scheduler issue fix will be released? I love this kernel and using Nox 17 is just not the same... :)

**Comment by kdrag0n** [comment] 2018-10-16 18:42
Here's a link to the current beta: https://t.me/velocity_s8/6138

**Comment by Jostian** [comment] 2018-10-16 19:04
Thanks, will give it a bash. But when i click on the link it opens a page but when i clink on the kernel link nothing happens, am i doing something wrong? Thanks

**Comment by Jostian** [comment] 2018-10-16 19:42
Ok had to join telegram group and have downloaded and installed the beta, the screen off rebooting bug is fixed, thanks. Will test for next day or so and get back to you on anything else. Cheers

**Comment by Jostian** [comment] 2018-10-17 05:01
The abox kernel wakelock is still there at the top of the battery drain list, battery drained 12% during sleep. Nox 17 and TGP have this wakelock butts it's like 1% of drain.

**Comment by kdrag0n** [comment] 2018-10-20 20:23
Reported as fixed in the Telegram group.

**Closed as completed by kdrag0n** 2018-10-20 20:23 UTC
